### ISSUE TITLE
Offensive021 - Admin can prevent users from claiming their rewards if the prize token is LINK

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#117]
Offensive021

Medium

# Admin can prevent users from claiming their rewards if the prize token is LINK

## Summary
An admin can unintentionally or intentionally prevent a winner from claiming their LINK token prize by allowing the contract's LINK balance to drop below the locked amount, violating the rule that winners must always be able to withdraw their rewards

## Vulnerability Detail
According to the [rules of this contest](https://audits.sherlock.xyz/contests/516):
> The principles that must always remain true are:
> - Winnables admins cannot do anything to prevent a winner from withdrawing their prize

However, if the prize token of a Raffle is the LINK token, an admin can, either intentionally or unintentionally, prevent the winner from claiming their reward. This occurs because the `_sendCCIPMessage` function reduces the fee from the amount that is locked for the Raffle, resulting in `linkToken.balanceOf(address(this)) < _tokensLocked[LINK]` and ultimately preventing the winner from claiming their reward.
```solidity
        uint256 fee = router.getFee(
            ccipDestChainSelector,
            message
        );
        uint256 currentLinkBalance = linkToken.balanceOf(address(this));

        if (fee > currentLinkBalance) {
            revert InsufficientLinkBalance(currentLinkBalance, fee);
        }
```

For better understanding, let's consider an example scenario:

- The admin transfers some LINK (let's say 2 LINK) to the `WinnablesPrizeManager.sol` to pay for fees.
- The admin locks 100 LINK to create a Raffle (the prize token for this Raffle is LINK).
- The admin also creates other Raffles, locking more NFTs, ETH, and tokens, which requires paying additional fees.
- These transactions result in 3 LINK being spent on fees—2 LINK from the amount that was deposited to pay for the fees plus 1 LINK deducted from the 100 LINK that was locked for the Raffle.
- Now, although the Raffle prize was initially set at 100 $LINK, the contract balance is only 99 LINK.
- When the winner calls the `claim` function, their transaction reverts because there is not enough LINK available to send to the winner.

An admin can do the above scenario either intentionally or unintentionally.

Despite the assumption that:

> Admins will always keep LINK in the contracts (to pay for CCIP Messages),

The implemented logic in the protocol allows an admin to prevent the winner from claiming their reward, which contradicts one of the principles:

> Winnables admins cannot do anything to prevent a winner from withdrawing their prize.

## Impact
Admin can prevent winners from getting their rewards which contradicts the principle:
 - Winnables admins cannot do anything to prevent a winner from withdrawing their prize.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/BaseCCIPSender.sol#L42

## Tool used

Manual Review

## Recommendation
Do not deduct fee from the prize amount:
```diff
    function _sendCCIPMessage(
        address ccipDestAddress,
        uint64 ccipDestChainSelector,
        bytes memory data,
+       uint256 lockedLink
    ) internal returns (bytes32 messageId) {
        if (ccipDestAddress == address(0) || ccipDestChainSelector == uint64(0)) {
            revert MissingCCIPParams();
        }

        // Send CCIP message to the desitnation contract
        IRouterClient router = IRouterClient(CCIP_ROUTER);
        LinkTokenInterface linkToken = LinkTokenInterface(LINK_TOKEN);

        Client.EVM2AnyMessage memory message = Client.EVM2AnyMessage({
            receiver: abi.encode(ccipDestAddress),
            data: data,
            tokenAmounts: new Client.EVMTokenAmount[](0),
            extraArgs: "",
            feeToken: LINK_TOKEN
        });

        uint256 fee = router.getFee(ccipDestChainSelector, message);
        uint256 currentLinkBalance = linkToken.balanceOf(address(this));
-         if (fee > currentLinkBalance) {
+         if (fee > (currentLinkBalance - lockedLink)) {
            //special case token link
            revert InsufficientLinkBalance(currentLinkBalance, fee);
        }

        messageId = router.ccipSend(ccipDestChainSelector, message);
    }
```

Duplicate of #277

**Comment by yashar0x** [comment]
escalate

as described [here](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/462), [here](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/350) and also [here](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/161) this issue is valid

**Comment by sherlock-admin3** [comment]
> escalate
> 
> as described [here](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/462), [here](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/350) and also [here](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/161) this issue is valid

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by mystery0x** [comment]
All admin related issues have been discussed with the HOJ and the sponsor who wished the following governing statements could have been more carefully written and/or omitted:

"The protocol working as expected relies on having an admin creating raffles. It should be expected that the admin will do their job. However it is not expected that the admin can steal funds that should have ended in a raffle participant’s wallet in any conceivable way."

Much as many of the findings suggest good fixes, the conclusion is that they will all be deemed low unless it's beyond the trusted admin control.

Also there’s this line: “Admins will always keep LINK in the contracts (to pay for CCIP Measages) and in the VRF subscription (to pay for the random numbers)” in the README, so in this case having not enough LINK would be against this line and a mistake.

**Comment by WangSecurity** [comment]
After additionally considering this issue, the escalation will be accepted and the issue will be validated with medium severity and duplicated with #277. For more details, look into the discussion under #277.

**Comment by WangSecurity** [comment]
This issue will be validated and duplicated with #277.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/18
