### ISSUE TITLE
Silvermist - WinnablesTicketManager.sol#withdrawTokens - Wrong check does not allow tokens withdraw

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#125]
Silvermist

High

# WinnablesTicketManager.sol#withdrawTokens - Wrong check does not allow tokens withdraw

## Summary
WinnablesTicketManager.sol#withdrawTokens - Wrong check does not allow tokens withdraw

## Vulnerability Detail
`withdrawTokens` function allows admin to withdraw accidentally sent token. 
```js
    function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
        if (amount < balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }
```
If the `amout` is less than the balance, it will revert with the `InsufficientBalance` error. It should check if  `amount > balance` because then there won't be enough balance.

The transaction won't revert only if `amount == balance` but a malisious user can front-run the withdraw and sent minimum amount of the token to make it fail. 

## Impact
Stuck of funds.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297
## Tool used

Manual Review

## Recommendation
```diff
    function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
-       if (amount < balance) revert InsufficientBalance();
+       if (amount > balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/6
