### ISSUE TITLE
boringslav - Withdraw tokens revert due to wrong check

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#145]
boringslav

High

# Withdraw tokens revert due to wrong check

## Summary
Wrong check for the amount of ERC20 tokens on `withdrawTokens` will make the function revert.

## Vulnerability Detail
In `WinnablesTicketManager.sol` the `withdrawTokens` function checks if the amount to withdraw is less than the token balance.  This will always be true and will make the function revert.
## Impact
`WinnablesTicketManager.sol::withdrawTokens` will always revert.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L295
```jsx
    function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
@>        if (amount < balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }

```
## Tool used

Manual Review

## Recommendation
```diff

function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {

	IERC20 token = IERC20(tokenAddress);
	uint256 balance = token.balanceOf(address(this));
-   if (amount < balance) revert InsufficientBalance();
+   if (balance < amount) revert InsufficientBalance();
	token.safeTransfer(msg.sender, amount);
}

```

**Comment by boringslav** [comment]
Escalate
With this check for the `amount` and `balance` the `withdrawTokens` function is basically useless and tokens will be stuck in the contract

**Comment by sherlock-admin3** [comment]
> Escalate
> With this check for the `amount` and `balance` the `withdrawTokens` function is basically useless and tokens will be stuck in the contract

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/6
