### ISSUE TITLE
boringslav - ERC721 cannot be sent to the PrizeManager via safeTransfer functions

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#156]
boringslav

High

# ERC721 cannot be sent to the PrizeManager via safeTransfer functions

## Summary
`WinnablesPrizeManager` is intended to hold prize items. However, because it does not implement the `onERC721Received()` function, it will not pass the checks for `safeTransferFrom()` and will not be able to be used for NFTs as intended. 

## Vulnerability Detail
As it is currently implemented the WinnablePrizeManager won't be able to receive NFTs sent by `safeTransfer`, `safeTransferFrom`,  and  `safeMint` because it doesn't implement the necessary

## Impact
Any time an ERC721 reward token is attempted to be transferred to the WinnablePrizeManager with a safe function it will revert

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesPrizeManager.sol#L18-L332

## Tool used

Manual Review

## Recommendation
Include `onERC721Received()` functions in `WinnablesPrizeManager.sol`.

### Note 
If ERC1155 are implemented in the future for rewards include the `onERC1155Received()` function

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/13
