### ISSUE TITLE
tjonair - M-1: `setCCIPCounterpart()` allows admin to deny raffle winner from claiming prize.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#163]
tjonair

Medium

# M-1: `setCCIPCounterpart()` allows admin to deny raffle winner from claiming prize.

### Summary

Using the function [`setCCIPCounterpart()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L238) to change the CCIPCounterpart address can deny winner from claiming their prize.

### Root Cause

The function [`setCCIPCounterpart()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L238) inherently is unaware about the current state of the contract.

```solidity
    function setCCIPCounterpart(
        address contractAddress,
        uint64 chainSelector,
        bool enabled
    ) external onlyRole(0) {
        _setCCIPCounterpart(contractAddress, chainSelector, enabled);
    }
```

In an Ideal scenario, when a raffle's duration is completed, the functions [`drawWinner()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L310) and [`propagateRaffleWinner()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L334) are to be called simultaneously by anyone in order to disburse prize to the winner.

In a case where a winner is drawn using [`drawWinner()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L310) and the admin decides to call [`setCCIPCounterpart()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L238) knowingly or unknowingly before the [`propagateRaffleWinner()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L334) call, will lead to denial of prize to that winner as it would never get propagated.

This violates the one of the principles mentioned by the protocol in `README.md`.
```Winnables admins cannot do anything to prevent a winner from withdrawing their prize```

### Internal pre-conditions

1. A raffle should have just passed it's designated duration

### Attack Path

1. Anyone calls the [`drawWinner()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L310) after a particular raffle has completed it's duration.
2. Admin will call the [`setCCIPCounterpart()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L238) function before anyone calls the [`propagateRaffleWinner()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L334)

### Impact

1. Raffle winner will be denied from claiming his prize.

Duplicate of #277

**Comment by WangSecurity** [comment]
After additionally considering this issue, the escalation will be accepted and the issue will be validated with medium severity and duplicated with #277. For more details, look into the discussion under #277.

**Comment by WangSecurity** [comment]
This issue will be validated and duplicated with #277.
