### ISSUE TITLE
0xrex - Smart accounts are prone to loss of raffle prizes won in the `WinnablesPrizeManager` contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#164]
0xrex

High

# Smart accounts are prone to loss of raffle prizes won in the `WinnablesPrizeManager` contract

## Summary
The `WinnablesPrizeManager` contract ensures that a raffle's winner must be the calling address/msg.sender during the claim of rewards in line #120 of the contract but forgets that the address/user that bought tickets on Avalanche on the `WinnablesTicketManager` contract will very likely not be the same on Ethereum mainnet. Hence, such chosen raffle prize winners get to lose their prizes as they cannot claim them on Ethereum and the prize cannot be retrieved by admins/owner either.

## Vulnerability Detail
```solidity
FILE: WinnablesTicketManager

function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        ...
@>        address winner = _getWinnerByRequestId(raffle.chainlinkRequestId); // @note selects winner

@>      _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner)); // @note sends a message to Prize manager on Ethereum to set selected winner as this raffle's winner
       ...
    }
```

```solidity
FILE: WinnablesTicketManager

function _getWinnerByRequestId(uint256 requestId) internal view returns(address) {
        RequestStatus storage request = _chainlinkRequests[requestId];
        uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(request.raffleId);
@>   uint256 winningTicketNumber = request.randomWord % supply; // @note gets a lucky number
@>       return IWinnablesTicket(TICKETS_CONTRACT).ownerOf(request.raffleId, winningTicketNumber); // @note finds owner of ticket token ID which matches lucky number and returns the owner address
    }
```

```solidity
FILE: WinnablesPrizeManager
function claimPrize(uint256 raffleId) external {
        ...
@>   if (msg.sender != rafflePrize.winner) revert UnauthorizedToClaim(); // @audit unfortunately the `rafflePrize.winner` is not the same person on this chain that controls the wallet that bought tickets on Avalanche chain because they use a smart account wallet and not the same address across chains
        ...
        emit PrizeClaimed(raffleId, msg.sender);
    }
```

## Impact
For such users, they will lose the raffle's prize that was delegated to them for winning the raffle and since the admin cannot withdraw the prize of a completed raffle, the prize will remain locked.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L105-L124
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L338
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L475-L476
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L340

## Tool used
Manual Review

## Recommendation
There are a couple of ways to resolve this issue whereby the user ends up getting their prize but some of the best are:

1. When selecting the winner of a raffle, check if there is a deployed code on the selected winner's address. If there is code, then have them claim their reward on the same chain which in this case is Avalanche but this also introduces another problem to think about in the case that what if the address has not yet been deployed aka has no code and not even an EOA anyone controls yet? Though unlikely, it is possible.
2. Users should be made aware that using smart account wallets causes a loss of prize risk if they do not control the same wallet on the other chain aka Ethereum.
3. Have a functionality to allow ticket buyers to specify addresses where they would like to receive their prize. Once this functionality is done, set that address as the address during winner propagation, and for users who do not specify, then they accept to mint to the same address used during ticket purchase.

**Comment by WangSecurity** [comment]
This issue will be validated with medium severity and duplicated with #122. For more info, refer to [this comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2348780200).
