### ISSUE TITLE
CatchEmAll - Wrong if check in `withdrawTokens()`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#167]
CatchEmAll

High

# Wrong if check in `withdrawTokens()`

## Summary

`WinnablesTicketManager.sol::withdrawTokens` is not working as intended.

## Vulnerability Detail

`withdrawTokens()` will always revert when authorized users (currently only the owner) try to withdraw any remaining ERC20 tokens. It will only work if they call it to withdraw the full amount, but this is not always the case.

The issue is due to a wrong balance check.

```solidity
function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
    IERC20 token = IERC20(tokenAddress);
    uint256 balance = token.balanceOf(address(this));
    if (amount < balance) revert InsufficientBalance();
    token.safeTransfer(msg.sender, amount);
}
```

If the specified amount is less than the available balance, the function will revert, which is not how the function should work - `if (amount < balance) revert InsufficientBalance();`

## Impact

ERC20 tokens cannot be transferred from `WinnablesTicketManager.sol`

## Code Snippet

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/e8b0603f6a155c7505dacc77194ae6789d0dbe7a/public-contracts/contracts/WinnablesTicketManager.sol#L295

## Tool used

Manual Review

## Recommendation

```diff
function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
    IERC20 token = IERC20(tokenAddress);
    uint256 balance = token.balanceOf(address(this));
-   if (amount < balance) revert InsufficientBalance();
+   if (amount > balance) revert InsufficientBalance();
    token.safeTransfer(msg.sender, amount);
}
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/6
