### ISSUE TITLE
CatchEmAll - Chainlink VRF 2.0 is deprecated

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#174]
CatchEmAll

Medium

# Chainlink VRF 2.0 is deprecated

## Summary

According to the Chainlink developers, VRF v2.0 will soon be deprecated and won’t be available to be used, making the `Winnables` protocol non-functional.

https://discord.com/channels/592041321326182401/722867054197080136/1250260870878068738

![Screenshot 2024-08-18 at 11.51.17 PM.png](https://i.imgur.com/1PoOIsK.png)

## Vulnerability Detail

There are few important modifications from v2.5 compared to v2.0 that will make the protocol non-compliant with the new VRF architecture:

- `subscriptionId` is now of type uint256, instead of `uint64`
- `requestRandomWords` now expect struct `RandomWordsRequest` and has one additional parameter `extraArgs`, that entirely changes the signature of the function.

The second change is most significant and it will prevent the protocol from drawing raffle winners.

Here are some evidences that the v2.0 will be deprecated and all the protocols should migrate to v2.5:

1. In Chainlink’s website there is only information about `VRF` v2.5 - https://docs.chain.link/vrf/v2-5/supported-networks#avalanche-mainnet
2. Chainlink devs advise to have way to upgrade the RNG provider, which is also lacking in the `Winnables` - https://discord.com/channels/592041321326182401/722867054197080136/1212405083741098004
    
    ![Screenshot 2024-08-19 at 12.02.01 AM.png](https://i.imgur.com/J42pZko.png)
    
3. V1 which also has been deprecated is entirely removed and can be used at all - https://discord.com/channels/592041321326182401/605768708266131456/1170984140447948820
4. The final date of deprecation for V2 is November 29, 2024, confirmed - https://discord.com/channels/592041321326182401/722867054197080136/1274768576582123611
    
    ![Screenshot 2024-08-19 at 12.05.28 AM.png](https://i.imgur.com/Aml0x99.png)
    

## Impact

`WinnablesTicketManager` will become non-functional when v2.0 is deprecated, preventing raffles from being settled, drawing winners and unlocking the rewards in `WinnablesPriceManager`

## Code Snippet

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L315-L321

## Tool used

Manual Review

## Recommendation

Migrate to v2.5 to ensure proper compatibility with the latest Chainlink contracts.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/21
