### ISSUE TITLE
joshuajee - Cross-chain transfer of winners address from Avalanche to Ethereum will lead to loss of winnings for multisig wallets.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#179]
joshuajee

High

# Cross-chain transfer of winners address from Avalanche to Ethereum will lead to loss of winnings for multisig wallets.

### Summary

According to the Readme, the WinnableaPrizeManager contract will be on Ethereum Mainnet and the WinnablesTicketManager  will be on Avalanche. Tickets are bought through the WinnablesTicketManager on Avalanche and after the raffle draw ends, the winner address is sent to the WinnableaPrizeManager  on Ethereum Mainnet for them to claim.

However, there is significant issue for users utilizing multisig wallets, as these wallets often have different addresses across different chains, preventing them from claiming their prize on Ethereum Mainnet.

### Root Cause

After a winner has been selected, they have to call the [propagateRaffleWinner](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334C5-L334C13) function to send a cross-chain message with the winner address to the WinnableaPrizeManager contract  on Ethereum Mainnet.

```sol
    function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.FULFILLED) revert InvalidRaffleStatus();
        raffle.status = RaffleStatus.PROPAGATED;
@>    address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);

@->  _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner));
        IWinnablesTicket(TICKETS_CONTRACT).refreshMetadata(raffleId);
        unchecked {
            _lockedETH -= raffle.totalRaised;
        }
    }
```

The [_ccipReceive](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L276) function receives the winner address then update it on Ethereum Mainnet which gives the winner the ability to claim prize, the problem here is that the address on Ethereum can be different from the on one avalanche for Multisig wallet users.

```sol
    function _ccipReceive(
        Client.Any2EVMMessage memory message
    ) internal override {
...
        (raffleId, winner) = _decodeWinnerDrawnMessage(message.data);
@->  _rafflePrize[raffleId].winner = winner;
        emit WinnerPropagated(raffleId, winner);
    }
```
Because of this difference in address between Ethereum and Avalanche the winner price will be lost for ever.

### Internal pre-conditions

1. The winner of the raffle must be a multisig wallet or smart account that have different addresses accross Ethereum Mainnet and Avalanche C chain.

### External pre-conditions

None

### Impact

Lose of winnings for winners with multisig wallets.

### Mitigation

1. Put a warning about multisig wallets.
2. Allow only the winner to call the `propagateRaffleWinner` function, they should provide an address on Mainnet that can claim on their behalf.

**Comment by WangSecurity** [comment]
This issue will be validated with medium severity and duplicated with #122. For more info, refer to [this comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2348780200).
