### ISSUE TITLE
Oblivionis - Admin can affect the odds of a raffle

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#191]
Oblivionis

Medium

# Admin can affect the odds of a raffle

## Summary

Admin can affect the odds of a raffle

## Vulnerability Detail

According to contest readme:

> The principles that must always remain true are:
> 
> Winnables admins cannot do anything to prevent a winner from withdrawing their prize
> Participants in a raffle that got cancelled can always get refunded
> Admins cannot affect the odds of a raffle

However, admin can directly mint Ticket by granting itself role 1.
```solidity
  function mint(address to, uint256 id, uint256 amount) external onlyRole(1) {
    if (to == address(0)) {
      revert TransferToAddressZero();
    }
    address operator = msg.sender;
    uint256 startId = _supplies[id];

    unchecked {
      _balances[id][to] += amount;
      _supplies[id] = startId + amount;
    }

    _ticketOwnership[id][startId] = to;
    emit NewTicket(id, startId, amount);
    emit TransferSingle(operator, address(0), to, id, amount);

    _doSafeTransferAcceptanceCheck(operator, address(0), to, id, amount);
  }
```

Current state of the Raffle is not checked when minting, meaning that admin can still mint tickets even if `raffle.status = RaffleStatus.REQUESTED` or `raffle.status == RaffleStatus.FULFILLED`. So admin can mint some new tickets after seeing VRF results to force himself to win the raffle.

Such behavior breaks the principle that "Admins cannot affect the odds of a raffle".

## Impact

Impact: high - a security principle can be broken

Likelihood: low - require a malicious admin

## Code Snippet

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L182

## Tool used

Manual Review

## Recommendation

`WinnablesTicket.mint` should check the status of current raffle.

Duplicate of #129

**Comment by Oblivionis214** [comment]
escalate 

not sure why this is invalid.

**Comment by sherlock-admin3** [comment]
> escalate 
> 
> not sure why this is invalid.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by BoRonG0d** [comment]
escalate

delegate to @Oblivionis214

**Comment by sherlock-admin3** [comment]
> escalate
> 
> delegate to @Oblivionis214 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
All admin related issues have been discussed with the HOJ and the sponsor who wished the following governing statements could have been more carefully written and/or omitted:

"The protocol working as expected relies on having an admin creating raffles. It should be expected that the admin will do their job. However it is not expected that the admin can steal funds that should have ended in a raffle participant’s wallet in any conceivable way."

Much as many of the findings suggest good fixes, the conclusion is that they will all be deemed low unless it's beyond the trusted admin control.

**Comment by WangSecurity** [comment]
The escalation will be accepted, the issue will be validated with medium severity and duplicated with #129. For details, look at the escalation under #129.

**Comment by WangSecurity** [comment]
Result:
Medium
Duplicate of #129

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BoRonG0d](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/191/#issuecomment-2334583400): accepted

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/20
