### ISSUE TITLE
Oblivionis - Smart contract wallet users may not be able to claim their prize

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#193]
Oblivionis

High

# Smart contract wallet users may not be able to claim their prize

## Summary

Currently `WinnablesTicketManager` simply forward winner's `msg.sender`(on Avalanche) to `WinnablesPrizeManager`(on Ethereum), which may not controlled by the real winner.

As a result, an attacker can gain control of the winner address of an account contract that was used to deposit assets from a chain into Root, by gaining control of the same address of the account contract that deposited the assets in a different chain.

As explained in detail on this [article written by Rekt](https://rekt.news/wintermute-rekt/), it is possible to gain control of the same address for contract accounts in a different chain; especially for those contract accounts that are deployed using the Gnosis Safe contracts.

## Vulnerability Detail

When winner is drawn, the winner's address(on Avalanche) will be sent directly to `WinnablesPrizeManager`(on Ethereum):

    function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.FULFILLED) revert InvalidRaffleStatus();
        raffle.status = RaffleStatus.PROPAGATED;
        address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);

        _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner));
        IWinnablesTicket(TICKETS_CONTRACT).refreshMetadata(raffleId);
        unchecked {
            _lockedETH -= raffle.totalRaised;
        }
    }

It incorrectly assumes that the address `raffle.winner` on Ethereum is owned by the same person on Avalanche chain. There are 2 cases when the assumption is not guaranteed:

Account Abstraction wallet implementations
old version of Safe multisigs https://rekt.news/wintermute-rekt/

## Impact

Users may not be able to claim their prize.

## Code Snippet

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334

## Tool used

Manual Review

## Recommendation

Add a function to allow users to change their participant address.

**Comment by Oblivionis214** [comment]
escalate

not sure why this is invalidated. It is very normal for a user to use a smart contract wallet, and this issue exist.

**Comment by sherlock-admin3** [comment]
> escalate
> 
> not sure why this is invalidated. It is very normal for a user to use a smart contract wallet, and this issue exist.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by BoRonG0d** [comment]
escalate

delegate to @Oblivionis214

**Comment by sherlock-admin3** [comment]
> escalate
> 
> delegate to @Oblivionis214 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
This has been discussed with the HOJ agreeing that this commonly known issue non-rewarded and something the protocol chooses not to fix. Users should know ahead of time whether or not the receiving address is the same as the sending address. AA is that generally validation can include any logic. EIP4337 for instance allows that as well (any limitations on the validation step are purely done off-chain and not guaranteed by the protocol).

**Comment by Oblivionis214** [comment]
Hi, I agree this is commonly known issue, but it is never mentioned in known issues and there is no statement that only EOA users can use winnables raffles. So I believe this issue is valid for current system.

https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/194
(As it is accepted is many previous audits)

**Comment by WangSecurity** [comment]
I agree with the lead judge that AA owners should be aware if they have the same address on different chains and it would be their responsibility to keep track of it and if they can receive funds to the same address on a different chain. Hence, I believe it's a user mistake, but of course, would be glad to hear the arguments for the opposite and might change my initial decision.

**Comment by Oblivionis214** [comment]
Hi @WangSecurity ! Wish you a good day!

I would argue that this kind of behavior shoud not be grouped with **user mistake** -- In contest Readme, it is not mentioned that users must have the control of same address on both Ethereum and Avalanche, and on some scenarios it is impossible for users to have the same address.

**Comment by WangSecurity** [comment]
After additionally considering this issue, I agree it should be valid with medium severity. Out of all the duplicates, I've picked #122 to be the main report. As for more information about the decision, please refer to [this comment under 122](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2348780200). Planning to accept the escalation and duplicate with #122

**Comment by WangSecurity** [comment]
UPD: track the discussion about this issue family under #122. If #122 is, in the end, invalid, planning to reject this escalation and leave the issue as it is. If #122 is valid, this escalation will be accepted, and this issue will be duplicated with #122.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BoRonG0d](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/193/#issuecomment-2329584539): rejected
