### ISSUE TITLE
p0wd3r - Drawable raffle can be canceled.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#210]
p0wd3r

Medium

# Drawable raffle can be canceled.

### Summary

Drawable raffle can be canceled.

### Root Cause

In `_checkShouldDraw`, `supply >= raffle.minTicketsThreshold` is required.
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L431
```solidity
        uint256 currentTicketSold = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
        if (currentTicketSold == 0) revert NoParticipants();

        if (block.timestamp < raffle.endsAt) {
            if (currentTicketSold < raffle.maxTicketSupply) revert RaffleIsStillOpen();
        }
        if (currentTicketSold < raffle.minTicketsThreshold) revert TargetTicketsNotReached();
``` 

In `_checkShouldCancel`, `supply <= raffle.minTicketsThreshold` is required.
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L440
```solidity
        if (raffle.endsAt > block.timestamp) revert RaffleIsStillOpen();
        uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
        if (supply > raffle.minTicketsThreshold) revert TargetTicketsReached();
``` 

So when `supply == raffle.minTicketsThreshold` and `block.timestamp >= raffle.endsAt`, this raffle can be both drawn and canceled.

This does not conform to the usage of the threshold, normally if it equals the threshold, it should not be canceled.

### Impact

This will lead to the cancellation of a raffle that could have been completed normally, users will waste time and the protocol will also failed to generate revenue.

### Mitigation

In `_checkShouldCancel`, `supply > raffle.minTicketsThreshold` -> `supply >= raffle.minTicketsThreshold`.

Duplicate of #26

**Comment by imp0wd3r** [comment]
Escalate

This is a valid Medium vulnerability that breaks the protocol's functionality, causing a raffle that could have been drawn to be canceled. Users will waste time and the protocol will also failed to generate revenue. These two functions should not overlap.

**Comment by mystery0x** [comment]
A fixed is desired to perfect the conditional check but it's deemed low given the trivial change needed.

**Comment by imp0wd3r** [comment]
I don't know what necessary connection "low" and "the trivial change needed" have.

Break the core functionality, should be medium.

**Comment by WangSecurity** [comment]
Planning to accept the escalation, validate with medium severity and duplicate with #26. For more details, see the discussion under #26.

**Comment by WangSecurity** [comment]
Result:
Medium
Duplicate of #26

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imp0wd3r](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/210/#issuecomment-2329397349): accepted

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/23
