### ISSUE TITLE
Silvermist - WinnablesPrizeManager.sol#claimPrize - User can double-claim the reward if a hard fork occurs

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#215]
Silvermist

High

# WinnablesPrizeManager.sol#claimPrize - User can double-claim the reward if a hard fork occurs

## Summary
User can double-claim the reward if a hard fork occurs

## Vulnerability Detail
If a hard fork occurs on the Ethereum Mainnet, the user can get his reward on both forked chains. This happens because there is no validation on the `chainId` and when a user is a winner nothing stops him from calling `claimPrize` on the old chain and the new forked one. Although he should receive his reward once, he will double-claim it.

## Impact
User can double-claim the reward
## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesPrizeManager.sol#L105-L124
## Tool used

Manual Review

## Recommendation
Cash the `chainId` in the constructor and check if the current `chainId` equals the cashed one inside `claimPrize`.

**Comment by 0xSilvermist** [comment]
Escalate

I understand that the likelihood is low but the impact is serious as users who win a raffle can claim their reward twice. Ethereum has already forked multiple times in the past so there is a possibility to hard fork again. See [Omni bridge](https://blocksecteam.medium.com/reveal-the-message-replay-attacks-on-ethereumpow-64e4feee991c) vulnerability for an example of what happened when Ethereum's transition to the PoS chain.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I understand that the likelihood is low but the impact is serious as users who win a raffle can claim their reward twice. Ethereum has already forked multiple times in the past so there is a possibility to hard fork again. See [Omni bridge](https://blocksecteam.medium.com/reveal-the-message-replay-attacks-on-ethereumpow-64e4feee991c) vulnerability for an example of what happened when Ethereum's transition to the PoS chain. 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
The sponsor already disputed this finding. It parallels the reentrancy issues that're just impractical to transpire and/or deemed low at best.

**Comment by rbserver** [comment]
#372 is similar to this.

**Comment by WangSecurity** [comment]
But who loses funds in this scenario?

**Comment by 0xSilvermist** [comment]
The total supply of the reward token will increase due to the double minting and the tokens will be devalued, this affects not only the users of the protocol but also anyone who holds the token that has been double minted.

**Comment by WangSecurity** [comment]
@0xSilvermist I'm not sure I understand how it works. For example, the prize was sent to Ethereum, it was forked before the winner got the prize. Then, the winner can get the reward on both the pre-fork Ethereum and post-fork Ethereum, correct?

But, where would they take the funds? The funds should not double during forks, i.e. you have 1 ETH on Ethereum pre-fork, then fork happens and you can get the 1 ETH on pre-fork Ethereum and 1 ETH on post-fork Ethereum, no?

I've read the article on omni bridge you linked, but it was a bridge, while here it's not a bridge, so I'm not sure how it works. Excuse me, if these are silly questions.

**Comment by 0xSilvermist** [comment]
Hey, @WangSecurity you understand it right, if the user was chosen, and a hard fork occurs before he claims his reward, when he claims his reward, he will be able to claim two rewards, although he won only one raffle. Also, it will affect a lot the reward token supply, if more than one user claims their rewards after the hard fork. 

I believe #372 and #584 are dupes of this because their root cause is the same. Their impact is serious too, because they can use one permit twice.

**Comment by jsmi0703** [comment]
This is invalid.
After hard fork occurs, the protocol will have funds in both forked chains. So although users claimed their reward in both forked chains, there is no loss of funds.
In more detail, assume that WinnablesPrizeManager had 100 ethers for rewards before hard fork. After hard fork, two forked WinnablesPrizeManagers will have 100 ethers respectively in both forked chains. After that, users will claim their rewards in both forked chains and take out 100 ethers respectively in both forked chains. So the reward process has executed successfully and there is no loss of funds or insolvency.

**Comment by Brivan-26** [comment]
Agree with the comment above. In addition, the pre-condition here is a hard fork happening on Ethereum, extremely low likelihood + the following rule should be applied:
> Chain re-org and network liveness related issues are not considered valid.
Exception: If an issue concerns any kind of a network admin (e.g. a sequencer), can be remedied by a smart contract modification, the protocol team considers external admins restricted and the considered network was explicitly mentioned in the contest README, it may be a valid medium. It should be assumed that any such network issues will be resolved within 7 days, if that may be possible.

**Comment by WangSecurity** [comment]
Yeah, I was thinking about what @jsmi0703 said and I agree, no one loses here, the winner should have been getting the prize and even tho they've got it twice due to the hard fork, still no one lost here. 

@Brivan-26 It's a good argument, but this rule only relates to re-org and sequencer-related issues. But, it's a very good thought that we may better include the hard fork here as well.

Planning to reject the escalation since there is no broken functionality and no loss of funds.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xSilvermist](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/215/#issuecomment-2333475224): rejected
