### ISSUE TITLE
p0wd3r - Admin can prevent winner from withdrawing prize

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#217]
p0wd3r

Medium

# Admin can prevent winner from withdrawing prize

### Summary

The admin can prevent the winner from claiming by changing `_ccipContracts[counterpart]`. Although this is an action taken by the admin, it violates the restrictions described in the documentation, so I consider it a valid vulnerability.

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/README.md#q-please-discuss-any-design-choices-you-made
> The principles that must always remain true are:
>
> Winnables admins cannot do anything to prevent a winner from withdrawing their prize

### Root Cause

The README had the following requirements written:
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/README.md#q-please-discuss-any-design-choices-you-made
> The principles that must always remain true are:
>
> Winnables admins cannot do anything to prevent a winner from withdrawing their prize

After selecting the winner in `tickerManger`, a message will be sent to `priceManager` via CCIP.
```solidity
    function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.FULFILLED) revert InvalidRaffleStatus();
        raffle.status = RaffleStatus.PROPAGATED;
        address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);

        _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner));
``` 

In the `ccipReceive` of `prizeManager`, `if (!_ccipContracts[counterpart]) revert UnauthorizedCCIPSender();`.
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L260-L265
```solidity
    function _ccipReceive(
        Client.Any2EVMMessage memory message
    ) internal override {
        (address _senderAddress) = abi.decode(message.sender, (address));
        bytes32 counterpart = _packCCIPContract(_senderAddress, message.sourceChainSelector);
        if (!_ccipContracts[counterpart]) revert UnauthorizedCCIPSender();
``` 

`_ccipContracts[counterpart]` can be set by admin.
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L134-L140
```solidity
    function setCCIPCounterpart(
        address contractAddress,
        uint64 chainSelector,
        bool enabled
    ) external onlyRole(0) {
        _setCCIPCounterpart(contractAddress, chainSelector, enabled);
    }
``` 

Therefore, if the admin wants to prevent a winner from withdrawing the reward, he can change the setting of `_ccipContracts[counterpart]` before `ccipReceive`, preventing the execution of `ccipReceive` and thus preventing the winner from claiming.

### Attack Path

1. `propagateRaffleWinner` selects Alice as the winner and sends a message to `priceManager` through CCIP.
2. Before `ccipReceive` is executed, the admin changes `_ccipContracts[counterpart]`, making the message that Alice is the winner unable to execute.
3. Even though Alice is marked as the winner in `tickerManager`, she is still unable to claim the reward.
4. If the admin wants to carry out a more targeted attack, they can use a sandwich attack-like approach, where they change `_ccipContracts` before Alice's `ccipReceive`, and then revert `_ccipContracts` to its original value after `ccipReceive` fails. This way, they disrupt Alice's claim without affecting subsequent functionality.

### Impact

Admin can prevent winner from withdrawing prize.

Duplicate of #277

**Comment by imp0wd3r** [comment]
Escalate

Break invariant in README. If this https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/236#issuecomment-2329537251 report is valid because of breaking README, this should also be valid.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Break invariant in README. If this https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/236#issuecomment-2329537251 report is valid because of breaking README, this should also be valid.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Brivan-26** [comment]
@imp0wd3r A similar issue was already escalated here #25

**Comment by mystery0x** [comment]
All admin related issues have been discussed with the HOJ and the sponsor who wished the following governing statements could have been more carefully written and/or omitted: 

"The protocol working as expected relies on having an admin creating raffles. It should be expected that the admin will do their job. However it is not expected that the admin can steal funds that should have ended in a raffle participant’s wallet in any conceivable way."

Much as many of the findings suggest good fixes, the conclusion is that they will all be deemed low unless it's beyond the trusted admin control.

**Comment by WangSecurity** [comment]
After additionally considering this issue, the escalation will be accepted and the issue will be validated with medium severity and duplicated with #277. For more details, look into the discussion under #277.

**Comment by WangSecurity** [comment]
Result:
Medium
Duplicate of #277

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imp0wd3r](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/217/#issuecomment-2331646087): accepted
