### ISSUE TITLE
shikhar - `_sendCCIPMessage` not validating destination contract and chain selector allows users to pass arbitrary values and leads to message not being delivered to desired contract, which further leads to multiple issues.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#231]
shikhar

High

# `_sendCCIPMessage` not validating destination contract and chain selector allows users to pass arbitrary values and leads to message not being delivered to desired contract, which further leads to multiple issues.

## Summary
- The `_sendCCIPMessage` involves sending a message to a contract on another chain, but it doesn't validate the destination contract address and the chain selector allowing users to pass arbitrary values via the functions: `cancelRaffle` and `propagateRaffleWinner`.
- There are also other functions which depends on `_sendCCIPMessage`, but as they are controlled by admin so it is expected that admin provides the correct input and doesn't do any mistake.
- Therefore, as there are sensitive functions that depends on `_sendCCIPMessage`  mentioned in first point, therefore it becomes mandatory to implement a validation on the arbitrary addresses passed, to prevent malicious users passing incorrect addresses which would result in message not being transferred to the destination contract.

## Vulnerability Detail
- The vulnerability occurs due to not validating arbitrary destination address and chain selector while sending a CCIP message.
- Functions such as `cancelRaffle` and `propagateRaffleWinner` depends on `_sendCCIPMessage` and both of these functions are callable by anyone.
- Both function expects a destination contract address and a chain selector to send the CCIP message, but these addresses are not validated. A malicious user passing arbitrary addresses prevent messages to be received on the desired contract.

## Impact
- For `cancelRaffle`: A malicious actor passing incorrect addresses would make the message not to be sent to the prize manager contract. The message involves conveying that raffle has been cancelled and to unlock the prize on prize manager, but as no message was transferred, it will get stuck forever in prize manager contract.
- For `propagateRaffleWinner`: A malicious actor passing incorrect addresses would make the message related to announcing a winner not to be sent on prize manager, as a result of which the deserving winner will never be able to claim their prize and the prize will be locked forever in prize manager contract.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/BaseCCIPSender.sol#L15

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L278

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334

## Tool used
Manual Review

## Recommendation
Add a check either in `_sendCCIPMessage` or every function involving arbitrary addresses and chain selectors that depends on `_sendCCIPMessage`, where the check only allows whitelisted destination contract addresses and chain selectors.

Duplicate of #50

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/22
