### ISSUE TITLE
CatchEmAll - Edge case allows users to decide the outcome of raffle

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#239]
CatchEmAll

Medium

# Edge case allows users to decide the outcome of raffle

## Summary

Users can decide whether to cancel or draw the winner of the raffle when it has a non-zero `minTicketsThreshold`.

## Vulnerability Detail

Let's look at all the functions that perform checks for a given raffle in `WinnablesTicketManager`: `_checkTicketPurchaseable`, `_checkShouldDraw`, and `_checkShouldCancel` we see the same pattern. They can be called when `block.timestamp == raffle.endsAt`:

```solidity
function _checkTicketPurchaseable(uint256 raffleId, uint256 ticketCount) internal view {
      Raffle storage raffle = _raffles[raffleId];
      if (block.timestamp > raffle.endsAt) revert RaffleHasEnded();//@audit can purchase at timestamp == endsAt
     ...MORE CODE
  }

```

```solidity
function _checkShouldDraw(uint256 raffleId) internal view {
      Raffle storage raffle = _raffles[raffleId];

      if (block.timestamp < raffle.endsAt) {
          if (currentTicketSold < raffle.maxTicketSupply) revert RaffleIsStillOpen();
      }
      if (currentTicketSold < raffle.minTicketsThreshold) revert TargetTicketsNotReached();
  }

```

```solidity
function _checkShouldCancel(uint256 raffleId) internal view {
      Raffle storage raffle = _raffles[raffleId];

      if (raffle.endsAt > block.timestamp) revert RaffleIsStillOpen();
      uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
      if (supply > raffle.minTicketsThreshold) revert TargetTicketsReached();
  }

```

Another pattern is the check for `minTicketsThreshold` in `_checkShouldDraw` and `_checkShouldCancel` - `supply == raffle.minTicketsThreshold` is not handled properly and both functions can be executed successfully when the supply is equal to the threshold.

Knowing that any user can decide the outcome of a raffle that has non-zero `minTicketsThreshold` and the supply has not reached yet, so depending on the incentive he can decide whether to draw a winner or cancel the raffle.

This can be used to grief users as the raffles are time-sensitive actions and cancel the raffle while indeed the `minTicketsThreshold` is reached as the supply is equal to it. Such actions can seriously harm the reputation of the protocol both for reward providers and ticket buyers.

The most straightforward execution is user to request multiple signatures, covering a wide range of ticket numbers in advance, then wait until the raffle is about to end while also monitoring the supply, and he can simply frontrun **anyone** who is willing to buy tickets that will bring the supply above the minimum, making the raffle non-cancelable. Attacker then can [stuff the block](https://www.bitcoininsider.org/article/45905/anatomy-block-stuffing-attack) with dummy transactions + his `WinnablesTicketManager::buyTicket` + `WinnablesTicketManager::cancelRaffle`. Stuffing the block will ensure no `buyTickets` will be executed in the very last second of the raffle from anyone different than the attacker.

This attack costs only gas, which is extremely low priced in Avalanche, to the executor, as the native assets used to buy the ticket can be refunded.

Rough estimation of stuffing an entire block in Avalanche [source](https://snowtrace.io/gastracker/cost-actions) - transactions that use 1 mln gas cost ~$0.56, gas limit of block 30 mln = ~$16.8

## Impact

Users can decide the outcome of the raffle due to missing check when `supply == minTicketsThreshold` in `WinnablesTicketManager::_checkShouldCancel`.

## Code Snippet

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L438-L439

## Tool used

Manual Review

## Recommendation

In `_checkShouldCancel` replace the following lines:

```diff
function _checkShouldCancel(uint256 raffleId) internal view {
      Raffle storage raffle = _raffles[raffleId];
      if (raffle.status == RaffleStatus.PRIZE_LOCKED) return;
      if (raffle.status != RaffleStatus.IDLE) revert InvalidRaffle();
-     if (raffle.endsAt > block.timestamp) revert RaffleIsStillOpen();
+     if (raffle.endsAt >= block.timestamp) revert RaffleIsStillOpen();
      uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
-     if (supply > raffle.minTicketsThreshold) revert TargetTicketsReached();
+     if (supply >= raffle.minTicketsThreshold) revert TargetTicketsReached();
  }
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/23
