### ISSUE TITLE
Penaldo - The `withdrawTokens()` function will not work due to incorrect if check

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#242]
Penaldo

Medium

# The `withdrawTokens()` function will not work due to incorrect if check

### Summary

The [`WinnablesTicketManager.sol::withdrawTokens()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function will revert due to the implemented [if check](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L295) being wrong. 

### Root Cause

The [if check](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L295) in the The [`WinnablesTicketManager.sol::withdrawTokens()`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function shown below checks if the inputted amount is less than the token balance of the contract. This check will cause the function to revert if the inputted amount is less than the token balance. 
```solidity
    function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
        if (amount < balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }
```
However, this check is wrong as it should revert when the inputted amount is greater than the token balance of the contract. As any amount would fail except when the `amount = balance`. In order to pass this if check, `amount` needs to be greater than or equal to the `balance`. If the `amount` is greater than the `balance` the `safeTransfer()` call would fail due to the contract not having enough tokens. If the `amount` is equal to the `balance`, this situation creates the possibility of front-running attacks where a user can send 1 wei token to the contract to make this function revert.

### Attack Path

As the function will always revert if the inputted amount is not equal to the balance:
1) Admin calls the `withdrawTokens()` function where the inputted `amount = balance`. (For easier understanding assume amount and balance are 100.)
2) Attacker front-run's this call to send 1 wei token to the contract.
3) Function checks the condition `if (amount < balance) revert InsufficientBalance();`
4) As the amount(100) is less than the balance (101), function will revert.

### Impact

It will be impossible for the admin to withdraw tokens from the contract.

### Mitigation

Change the if check in the function as shown below:
```solidity
    function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
        if (amount  > balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }
```
An alternative fix can be implemented as shown below:
```solidity
    function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
        if (amount  > balance){
        amount = balance; }
        token.safeTransfer(msg.sender, amount);
    }
```

**Comment by utkuerkin** [comment]
Escalate

Most of the duplicates of this report do not consider a front-running DoS risk. This report clearly shows a very easy to do DoS that will lead to funds being locked in the contract. Likelihood of this is High/Medium and Impact is Medium therefor this report and others that mention the front-running DoS risk should be a valid Medium. Reports that do not mention the front-running risk should stay as Low severity.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Most of the duplicates of this report do not consider a front-running DoS risk. This report clearly shows a very easy to do DoS that will lead to funds being locked in the contract. Likelihood of this is High/Medium and Impact is Medium therefor this report and others that mention the front-running DoS risk should be a valid Medium. Reports that do not mention the front-running risk should stay as Low severity.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/6
