### ISSUE TITLE
dimulski - Winners of raffles who use account abstraction wallets won't be able to claim their rewards.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#260]
dimulski

Medium

# Winners of raffles who use account abstraction wallets won't be able to claim their rewards.

### Summary

Users who use account abstraction wallets and win a raffle won't be able to claim their rewards via the [claimPrize()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L105-L124) function. Account abstraction wallets are, by design, unique smart contract instances deployed on individual chains. While users can create account abstraction wallets on different chains, they ultimately have distinct account addresses. Since account abstraction wallets are on the rise, with Safe having almost 6M users (disregarding other Account Abstraction wallet "providers"), this is a very plausible scenario that should be taken into consideration.
The ``WinnablesPrizeManager.sol`` contract is  going to be deployed on Ethereum and the ``WinnablesTicketManager.sol`` and ``WinnablesTicket.sol`` contracts are going to be deployed on Avalance. When a winner for a raffle is drawn, the [propagateRaffleWinner()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345) function has to be called:
```solidity
    function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.FULFILLED) revert InvalidRaffleStatus();
        raffle.status = RaffleStatus.PROPAGATED;
        address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);

        _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner));
        IWinnablesTicket(TICKETS_CONTRACT).refreshMetadata(raffleId);
        unchecked {
            _lockedETH -= raffle.totalRaised;
        }
    }
```
The [propagateRaffleWinner()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345) function internally calls the [_getWinnerByRequestId()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L472-L477) function which returns the address that owns the winning NFT ID at Avalance, this address will be set as the winner of the raffle in the ``WinnablesPrizeManager.sol`` contract on Ethreum. 
The address of the owner of the winning NFT on Avalanche may not exist on Ethereum or be controlled by someone else. 
### Root Cause

The possible use of account abstraction wallets is overlooked by the Winnables team. 

### External pre-conditions

1. Winner of a raffle has to use an account abstraction wallet.

### Impact

Users who use account abstraction wallets and win a raffle won't be able to claim their rewards via the [claimPrize()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L105-L124) function. The prize will be forever locked in the ``WinnablePrizeManager.sol`` contract.

### Mitigation

Consider allowing only the winner of a certain raffle to call the  [propagateRaffleWinner()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345) function and set an address that he wants as the winner of the raffle.

**Comment by AtanasDimulski** [comment]
Escalate,
Account abstraction wallets are becoming more widely used every day, the possibility of users utilizing such accounts to buy a ticket for the raffle is pretty high, given one of the main selling points of the protocol is that users can buy tickets on Avalanche, where gas is way cheaper, and receive their rewards on Ethereum. The impact is high - users won't be able to collect their rewards, and they would have already spent ETH to buy the NFT. The probability is medium I would say, thus I believe medium severity for this issue is appropriate.

**Comment by sherlock-admin3** [comment]
> Escalate,
> Account abstraction wallets are becoming more widely used every day, the possibility of users utilizing such accounts to buy a ticket for the raffle is pretty high, given one of the main selling points of the protocol is that users can buy tickets on Avalanche, where gas is way cheaper, and receive their rewards on Ethereum. The impact is high - users won't be able to collect their rewards, and they would have already spent ETH to buy the NFT. The probability is medium I would say, thus I believe medium severity for this issue is appropriate. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Brivan-26** [comment]
Likelihood is Medium with High impact makes it High severity.
#157 is a dup of this

**Comment by debugging3** [comment]
#122, #193, #255 is also a dup of this.

**Comment by 4rdii** [comment]
[241](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/241) any many others also stated same, no reason was given in any of them!

**Comment by rexjoseph** [comment]
dupe #164

**Comment by Blngogo** [comment]
#319 this guy's report is also a dup of this

**Comment by mystery0x** [comment]
This has been discussed with the HOJ agreeing that this commonly known issue non-rewarded and something the protocol chooses not to fix. Users should know ahead of time whether or not the receiving address is the same as the sending address. AA is that generally validation can include any logic. EIP4337 for instance allows that as well (any limitations on the validation step are purely done off-chain and not guaranteed by the protocol).

**Comment by AtanasDimulski** [comment]
Hey @mystery0x thanks for your feedback. However, in all your comments I have seen so far, it seems like you and the HOJ are having some private discussion that overwrites Sherlock rules. This is not a commonly known issue and is usually judged as High, or Med. I can provide you with examples if you want. This issue has nothing to do with how transaction executions are handled in AA. Lastly what the protocol chooses to fix doesn't determine whether an issue is valid or not. Thank you for your time!

**Comment by WangSecurity** [comment]
What I agree with the LJ on is that indeed the owner of AA wallet should be aware they don't control the same addresses on different chains and it's their responsibility. But, would be glad to hear the arguments against it

**Comment by Blngogo** [comment]
@WangSecurity Sir, if this is considered as a known issue, shouldn't it be mentioned in the "known issues" section of the README?   Also the code in-scope doesn't provide any restrictions of users participating using smart contracts, which is why i believe watsons submitted it. As an example, can provide few reports of such issues considered as Medium or even High. Generally, the protocol doesn't aware it's users that only EOA's will be supported. This will result in permanently stuck funds, thus bricks the purpose of the raffle. I think this is not the intention of the protocol, and i wonder why the sponsor doesn't want to fix it, although the recommended fixes in the reports are very simple and effective.

**Comment by Brivan-26** [comment]
@WangSecurity 
> indeed the owner of AA wallet should be aware they don't control the same addresses on different chains and it's their responsibility

This wasn't mentioned anywhere in the contest README as known issue

**Comment by AtanasDimulski** [comment]
Hey @WangSecurity, first of all, I want to mention that the fact this was not specified in the readme, or anywhere in the public chat while the contest was running, should be enough to validate this issue. There is no Sherlock rule that makes this invalid. Here are some recent examples when similar issues were judged as valid Highs [example1](https://codehawks.cyfrin.io/c/2024-01-Morpheus/s/237), [example2](https://solodit.xyz/issues/incompatibility-with-multisig-wallets-in-templegoldsend-function-codehawks-templegold-git). I can provide more if you are not convinced. Secondly, typically in cross-chain protocols when some tokens have to be received on another chain, users are supposed to provide the correct address that should receive the tokens. Lastly, I want to clarify that this is not a design decision, whether the sponsor was aware of how account abstraction wallets work before the audit is of no concern.

**Comment by WangSecurity** [comment]
After additionally considering this issue, I agree it should be valid with medium severity. Out of all the duplicates, I've picked #122 to be the main report. As for more information about the decision, please refer to [this comment under 122](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2348780200). Planning to accept the escalation and duplicate with #122

**Comment by WangSecurity** [comment]
UPD: track the discussion about this issue family under #122. If #122 is, in the end, invalid, planning to reject this escalation and leave the issue as it is. If #122 is valid, this escalation will be accepted, and this issue will be duplicated with #122.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/260/#issuecomment-2329503364): rejected
