### ISSUE TITLE
Silvermist - WinnablesTicketManager.sol#_checkShouldCancel - Wrong check allows raffle to be canceled even though it shouldn't be

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#272]
Silvermist

Medium

# WinnablesTicketManager.sol#_checkShouldCancel - Wrong check allows raffle to be canceled even though it shouldn't be

## Summary
Wrong check allows a raffle to be canceled even though it shouldn't be.

## Vulnerability Detail
Users are allowed to cancel a raffle with `cancelRaffle` and return their money. A raffle can be canceled if three conditions are met:
- the raffle status is IDLE
- the raffle ended
- the raffle supply is **LESS** than the minimum allowed. 

These checks are done inside `_checkShouldCancel`:
```js
    function _checkShouldCancel(uint256 raffleId) internal view {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status == RaffleStatus.PRIZE_LOCKED) return; // pass
        if (raffle.status != RaffleStatus.IDLE) revert InvalidRaffle(); // pass 
        if (raffle.endsAt > block.timestamp) revert RaffleIsStillOpen(); // pass
        uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
        if (supply > raffle.minTicketsThreshold) revert TargetTicketsReached();
    }
```
As we can see, the last if checks that the `supply` is more than the `minTicketsThreshold`. If that's true, the cancellation is not allowed and it will revert. However, if the `supply` is equal to the `minTicketsThreshold` this check will pass and the raffle can be canceled. The problem is, if the `supply` is equal to the `minTicketsThreshold` the raffle is eligible and should not be canceled.

## Impact
Wrong check allows a raffle to be canceled even though it shouldn't be.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L440
## Tool used

Manual Review

## Recommendation
```diff
    function _checkShouldCancel(uint256 raffleId) internal view {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status == RaffleStatus.PRIZE_LOCKED) return;
        if (raffle.status != RaffleStatus.IDLE) revert InvalidRaffle();
        if (raffle.endsAt > block.timestamp) revert RaffleIsStillOpen();
        uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
-        if (supply > raffle.minTicketsThreshold) revert TargetTicketsReached();
+        if (supply >= raffle.minTicketsThreshold) revert TargetTicketsReached();
    }
```

Duplicate of #26

**Comment by 0xSilvermist** [comment]
Escalate 

I believe this is a valid finding as it allows to sabotage a raffle. Raffle should be canceled **ONLY** if `supply < minTicketsThreshold`, if `supply = minTicketsThreshold` raffle meets the criteria to draw a winner, however, this wrong check allows filly eligible raffle to be canceled.

**Comment by mystery0x** [comment]
A fixed is desired to perfect the conditional check but it's deemed low given the trivial change needed.

**Comment by 0xSilvermist** [comment]
I respectfully disagree because of a few reasons.

First, how does the recommendation change determines the severity? Yeah, it is only one = but it fixes a serious problem, and the severity should be determined from the impact.

Second, Sherlock docs state that an issue is with Medium severity if it [breaks core contract functionality](https://docs.sherlock.xyz/audits/judging/judging#v.-how-to-identify-a-medium-issue:~:text=Breaks%20core%20contract%20functionality). The whole protocol logic relies on raffle creation and this breaks the creation. I understand the likelihood of `supply` being equal to `minTicketsThreshold` is low but the impact is serious. Also, the sponsor emphasized that a raffle must be created if `supply == minTicketsThreshold`.

**Comment by WangSecurity** [comment]
Planning to accept the escalation, validate with medium severity and duplicate with #26. For more details, see the discussion under #26.

**Comment by WangSecurity** [comment]
Result:
Medium
Duplicate of #26

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xSilvermist](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/272/#issuecomment-2329325704): accepted
