### ISSUE TITLE
dimulski - Admin can easily break core protocol invariants and affect the odds of a raffle winner

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#303]
dimulski

High

# Admin can easily break core protocol invariants and affect the odds of a raffle winner

### Summary

In the readme of the contest it is specifically stated that admins are not fully trusted: *Admins cannot affect the odds of a raffle* & *The existence of max ticket supply and max holdings however guarantees a minimum level of fairness in that raffle participants can be sure that by purchasing tickets, they have a hard minimum odds of winning equal to numberOfTicketsPuchased / totalTicketSupply.* The minimum level of fairness however is not strictly enforced in the [mint()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L182-L199) function. An admin has role 0, and he can give role 1 (which is the minter role) to whomever he wishes.  When a raffle is fully set up by an admin via the [createRaffle()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L252-L274) function, parameters such as **raffle.maxTicketSupply** and **raffle.maxHoldings** are set to guarantee that users who bought tickets have a fair chance of winning the raffle, no matter how much NFTs are minted by the admin, or another account the admin has given role 1. As can be seen the [mint()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L182-L199) function doesn't enforce this restrictions: 
```solidity
  function mint(address to, uint256 id, uint256 amount) external onlyRole(1) {
    if (to == address(0)) {
      revert TransferToAddressZero();
    }
    address operator = msg.sender;
    uint256 startId = _supplies[id];

    unchecked {
      _balances[id][to] += amount;
      _supplies[id] = startId + amount;
    }

    _ticketOwnership[id][startId] = to;
    emit NewTicket(id, startId, amount);
    emit TransferSingle(operator, address(0), to, id, amount);

    _doSafeTransferAcceptanceCheck(operator, address(0), to, id, amount);
  }
```
The **raffle.maxTicketSupply** and **raffle.maxHoldings** are of type **uint32**, so the max number of minted tickets is expected to be **4294967295**. However a minter can mint up to **type(uint256).max** ticket NFTs by directly calling the [mint()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L182-L199) function. This breaks the fairness invariant of the protocol. Secondly when a raffle is drawn  first the [drawWinner()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L310-L329) function is called in order to request a random word from Chainlink VRF. When the [drawWinner()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L310-L329) function is called, the status of the raffle is set to  **REQUESTED**, and users can no longer mint NFTS via the [buyTickets()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L182-L210) function. The VRFCordinator then calls the [fulfillRandomWords()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L350-L361) function when he is ready with the answer. However the winner of the raffle is not set when the VRFCordinator calls the [fulfillRandomWords()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L350-L361) function. The winner of the raffle is set when [propagateRaffleWinner()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345) is called which internally calls the [_getWinnerByRequestId()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L472-L477) function:
```solidity
    function _getWinnerByRequestId(uint256 requestId) internal view returns(address) {
        RequestStatus storage request = _chainlinkRequests[requestId];
        uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(request.raffleId);
        uint256 winningTicketNumber = request.randomWord % supply;
        return IWinnablesTicket(TICKETS_CONTRACT).ownerOf(request.raffleId, winningTicketNumber);
    }
```
Once the VRF request is fulfilled, the admin can read from the blockchain the random word returned from the VRFCordinator and calculate which NFT ID is going to be the winner of the raffle 
```solidity
uint256 winningTicketNumber = request.randomWord % supply;
```
The admin (or minter controller by the admin) can mint additional NFTs to increase the supply and thus change the winner. In most cases the admin will be able to set the winningTicketNumber to an NFT he owns. Keep in mind that users can only mint up to **4294967295** NFTs, and the admin can mint up to **type(uint256).max** which is much bigger number. This breaks the core protocol invariant that the admin shouldn't affect the odds of a raffle, and effectively steals funds from the users who bought tickets. 

### Root Cause
Restrictions set by the admin when creating the raffle via the [createRaffle()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L252-L274) function, such as **raffle.maxTicketSupply** and **raffle.maxHoldings** are not enforced in the [mint()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L182-L199) function. The admin can continue to mint NFTs even after the raffle has been drawn.

### Attack Path
I have used smaller numbers to better illustrate the severity of this vulnerability 
1. Three different users buy 1 ticket each, now there are NFTs with IDs 0, 1, 2 and supply is 3, the returned random word is 10
2. The admin sees that the VRFCordinator has responded with a random word and calculates that *10 % 3 = 1*, so the winner of the raffle should be the owner of the NFT with ID 1. 
3. The admin calls the [mint()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L182-L199) function, and mint 4 NFTs to an address he controls, now the NFT IDs are 0, 1, 2, 3 and the supply is 7. 
4. The admin has changed the winner of the raffle *10 % 7 = 3*, now the winner is the owner of NFT with ID 3, which is owned by an address that is controlled by the admin. The admin now calls the [propagateRaffleWinner()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345) function, to propagate the winner to the ``WinnablesPrizeManager.sol`` contract. The [propagateRaffleWinner()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345) function is permissionless and anybody can call it, but the admin can fronturn the call and first mint the required numbers of NFTs to manipulate the winner of the raffle if needed. 

### Impact
Core invariants of the protocol can be easily broken, and in most cases a malicious admin can effectively steal funds from the users who bought tickets. When the winner of a raffle is propagated to the ``WinnablesPrizeManager.sol`` contract, the admin can withdraw the proceeds from users buying tickets, and when an address he controls claims the prize that the admin staked when creating the raffle, users of the protocol are left with nothing, thus the high severity. 

### Mitigation

Enforce the restrictions set by the admin when creating the raffle via the [createRaffle()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L252-L274) function, in the [mint()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L182-L199) function. Also check what is the raffle status, if it is different than IDLE don't allow for any more mints. 

Duplicate of #129

**Comment by AtanasDimulski** [comment]
Escalate,
Since there are no comments provided as to why the judge believes this issue is invalid, I am guessing it is because the judge has assumed that the admin is trusted, however in the README it is specified that admins are not fully trusted: *Admins cannot affect the odds of a raffle & The existence of max ticket supply and max holdings however guarantees a minimum level of fairness in that raffle participants can be sure that by purchasing tickets, they have a hard minimum odds of winning equal to numberOfTicketsPuchased / totalTicketSupply*.

**Comment by sherlock-admin3** [comment]
> Escalate,
> Since there are no comments provided as to why the judge believes this issue is invalid, I am guessing it is because the judge has assumed that the admin is trusted, however in the README it is specified that admins are not fully trusted: *Admins cannot affect the odds of a raffle & The existence of max ticket supply and max holdings however guarantees a minimum level of fairness in that raffle participants can be sure that by purchasing tickets, they have a hard minimum odds of winning equal to numberOfTicketsPuchased / totalTicketSupply*.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0x-Shahil-Hussain** [comment]
#482 is a dup of this

**Comment by Brivan-26** [comment]
Agree with the escalation. The random winner is selected based on the `randomword`. After the random word is fulfilled, an admin can call `WinableTicket::mint` directly to mint the necessary amount of tickets and manipulate the `supply` to control the winner, based on the selection formula: `request.randomWord % supply;`
#79 is a dup of this

**Comment by mystery0x** [comment]
All admin related issues have been discussed with the HOJ and the sponsor who wished the following governing statements could have been more carefully written and/or omitted:

"The protocol working as expected relies on having an admin creating raffles. It should be expected that the admin will do their job. However it is not expected that the admin can steal funds that should have ended in a raffle participant’s wallet in any conceivable way."

Much as many of the findings suggest good fixes, the conclusion is that they will all be deemed low unless it's beyond the trusted admin control.

**Comment by AtanasDimulski** [comment]
Hey @mystery0x, thanks for your feedback. However I am not aware of what you have discussed with the sponsor and HOJ, and frankly, it doesn't matter. Sherlock rules are pretty clear: *If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth.* & *Direct Protocol Owner/Admin rug pulls. If a protocol specifically mentions the restrictions imposed on the owner/admin, issues describing an attack that results in bypassing these restrictions can be considered valid.*. If the sponsor wanted to clarify the government statements he had time to do so, as Sherlock allows the README to be updated up to 24 hours before the contest ends. In the README it is clearly stated that:

**The principles that must always remain true are:**
 - Admins cannot affect the odds of a raffle
 - It is not expected that the admin can steal funds that should have ended in a raffle participant’s wallet in any conceivable way.
- The existence of max ticket supply and max holdings however guarantees a minimum level of fairness in that raffle participants can be sure that by purchasing tickets, they have a hard minimum odds of winning equal to numberOfTicketsPuchased / totalTicketSupply.

The above listed principles are as invariants, and specific scenarios where admins are not trusted have been specifically described throughout the whole readme. Not accepting those issues goes against Sherlock rules. Thanks for your time

**Comment by WangSecurity** [comment]
The escalation will be accepted, the issue will be validated with medium severity and duplicated with #129. For details, look at the escalation under #129.

**Comment by WangSecurity** [comment]
Result:
Medium
Duplicate of #129

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/303/#issuecomment-2329491593): accepted

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/20
