### ISSUE TITLE
0xMosh - users with account abstraction wallet may loose their prize .

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#307]
0xMosh

Medium

# users with account abstraction wallet may loose their prize .

### Summary

Current design of the protocol assumes users to have the same address in avalanche and Ethreum and releases the winning pot to winner in eth chain  . But thats not the case for account abstraction wallets . Account abstraction wallets may have different addresses in different chains . If this is the case for an winner of  a raffle , he will lose his winning prize .

### Root Cause
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334
```solidity 
 function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.FULFILLED) revert InvalidRaffleStatus();
        raffle.status = RaffleStatus.PROPAGATED;
        address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);

   @>   _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner)); 
        IWinnablesTicket(TICKETS_CONTRACT).refreshMetadata(raffleId);
        unchecked {
            _lockedETH -= raffle.totalRaised;
        }
    }

```
`winner` here is the address of winner in Avalanche chain and the winning prize is now claimable for `winner ` in Ethereum chain . User having an account abstraction wallet  will lose all of his prize if he have  different addresses in Avalanche and Ethereum chain . 

### External pre-conditions

User needs to have an account abstraction wallet which is pretty common . 

### Impact

Winner will lose all of his winning prize and funds will be stuck in the contract forever . 

### Mitigation

Put an additional `to` field of prize receiving address in ethereum chain  while buying tickets .

**Comment by WangSecurity** [comment]
This issue will be validated with medium severity and duplicated with #122. For more info, refer to [this comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2348780200).
