### ISSUE TITLE
dimah7 - Winners can't claim the prize, if using AA wallets or multisig wallets

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#319]
dimah7

High

# Winners can't claim the prize, if using AA wallets or multisig wallets

## Summary

Protocol will be incompatible with some AA wallets or multisig wallets. By design, the project works like this:

1. The raffle prize is locked on the Prize Manager contract, which will be deployed on Ethereum mainnet
2. Users participate by buying tickets and later on a random winner is chosen through Chainlink's VRF services, all this functionality happens on the Ticket Manager contract, which will be deployed on Avalanche network
3. Then the raffle winner data is sent to the Prize Manager utilizing Chainlink's CCIP
4. The winner can claim his reward from the Prize Manager on Mainnet

Some users may use Account Abstraction wallets or multisig wallets to participate in the raffles. This is problematic, since different wallets will have different addresses on different chains. 

## Vulnerability Detail

Let's follow how the winner is picked and then how the message is received: 

- When `WinnablesTicketManager::propagateRaffleWinner()` is called it selects the winner and then makes the cross-message delivery to the Prize Manager with the necessary information, where the reward becomes claimable for the winner:

```javascript
function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.FULFILLED) revert InvalidRaffleStatus();
        raffle.status = RaffleStatus.PROPAGATED;
@>      address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);
                                                                                                                      !!!!!!
@>      _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner));
        IWinnablesTicket(TICKETS_CONTRACT).refreshMetadata(raffleId);
        unchecked {
            _lockedETH -= raffle.totalRaised;
        }
    }
```

And here is how the message is received in the Prize Manager, what is of our concern is how the winner's data is handled:

```javascript
function _ccipReceive(
        Client.Any2EVMMessage memory message
    ) internal override {
        (address _senderAddress) = abi.decode(message.sender, (address));
        bytes32 counterpart = _packCCIPContract(_senderAddress, message.sourceChainSelector);
        if (!_ccipContracts[counterpart]) revert UnauthorizedCCIPSender();

        CCIPMessageType messageType = CCIPMessageType(uint8(message.data[0]));
        uint256 raffleId;
        address winner;
        if (messageType == CCIPMessageType.RAFFLE_CANCELED) {
            raffleId = _decodeRaffleCanceledMessage(message.data);
            _cancelRaffle(raffleId);
            return;
        }
        (raffleId, winner) = _decodeWinnerDrawnMessage(message.data);
@>       _rafflePrize[raffleId].winner = winner;
        emit WinnerPropagated(raffleId, winner);
    }
```

As we notice from above, it populates the `_rafflePrize` mapping with the returned winner and raffle id data. So the returned address is the same as from Avalanche network. And since smart contract wallets are chain-specific because of the nonce, when a winner tries to withdraw from `WinnablesPrizeManager::claimPrize()`, the call will revert: 

```javascript
function claimPrize(uint256 raffleId) external {
        RafflePrize storage rafflePrize = _rafflePrize[raffleId];
        ...
        if (msg.sender != rafflePrize.winner) revert UnauthorizedToClaim();
        ...
    }
```

## Impact

- High: as a user will not be able to claim his prize, this completely breaks one of the main invariants of the protocol

## Code Snippet

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L338-L340
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L472-L476
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesPrizeManager.sol#L275-L276
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesPrizeManager.sol#L120

## Tool used

Manual Review

## Recommendation

Allow only EOA's to participate or utilize the CREATE2 method to predict the addresses, by providing the same salt on the different chains.

**Comment by WangSecurity** [comment]
This issue will be validated with medium severity and duplicated with #122. For more info, refer to [this comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2348780200).
