### ISSUE TITLE
Waydou - Inconsistency Between Documentation and Implementation in Raffle Finalization Conditions

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#320]
Waydou

Medium

# Inconsistency Between Documentation and Implementation in Raffle Finalization Conditions

### Summary

There is a critical discrepancy between the documented behavior and the actual implementation of the raffle finalization process. The documentation states that it becomes possible to draw a winner when "the time runs out and the minimum number of tickets was reached.The time runs out and the minimum number of tickets wasn’t reached: it becomes possible to cancel the raffle " However, the implemented logic allows for cancellation under conditions that should, according to the documentation, result in a winner being drawn instead.

### Root Cause

The root cause of this issue is a mismatch between the documented design intent and the actual smart contract implementation.https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L440
 Specifically, the conditions for canceling a raffle overlap with conditions that should allow for drawing a winner, leading to potential confusion and unexpected outcomes.

### Internal pre-conditions

A raffle has been created and is past its end time.
The number of tickets sold is equal to the minimum threshold.

### External pre-conditions

None specific; this issue is inherent to the contract's logic.

### Attack Path

1. A raffle is created with a minimum ticket threshold and a maximum ticket supply.
2. The raffle end time passes, and the number of tickets sold is at the minimum threshold.
3. According to the documentation, this should result in a winner being drawn.
4. However, an actor (malicious or otherwise) can call the cancelRaffle function.
The cancellation succeeds, despite the conditions meeting those described for winner selection.

### Impact

Potential loss of trust from participants who expect a winner to be drawn.

### Mitigation

function _checkShouldCancel(uint256 raffleId) internal view {
    Raffle storage raffle = _raffles[raffleId];
    if (raffle.status != RaffleStatus.IDLE) revert InvalidRaffle();
    if (block.timestamp <= raffle.endsAt) revert RaffleIsStillOpen();
    uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
+   if (supply > raffle.minTicketsThreshold) revert CannotCancelValidRaffle();
-   if (supply >= raffle.minTicketsThreshold) revert CannotCancelValidRaffle();
}

**Comment by Waydou21** [comment]
Why is this excluded if the sponsor confirmed it's valid?

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/23
