### ISSUE TITLE
dimah7 - If a raffle winner gets blacklisted by USDC, raffle admin's locked tokens will be permanently stuck

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#328]
dimah7

Medium

# If a raffle winner gets blacklisted by USDC, raffle admin's locked tokens will be permanently stuck

## Summary

As per protocol's README, USDC is one of the tokens which will be allowed to interact with the project. And as per the updated README: "For tokens that have a blacklist, we will ignore any issues caused by that blacklist unless they cause damage to the protocol or other users.".

A well-known feature of the USDC token is that it has a blacklist functionality. The case here is that if a raffle winner gets blacklisted, he will not be able to claim his prize, i think this will be fine by the protocol as it's expected behaviour, but the greater impact is that the USDC raffle admin can't withdraw his funds as they will stay permanently locked

## Vulnerability Detail

Following the lock function: 

```javascript
function lockTokens(
        address ticketManager,
        uint64 chainSelector,
        uint256 raffleId,
        address token,
        uint256 amount
    ) external onlyRole(0) {
        RafflePrize storage rafflePrize = _checkValidRaffle(raffleId);
        uint256 tokenBalance = IERC20(token).balanceOf(address(this));
        if (tokenBalance < amount + _tokensLocked[token]) revert InvalidPrize();
        rafflePrize.raffleType = RaffleType.TOKEN;
        unchecked { _tokensLocked[token] += amount; }
        _tokenRaffles[raffleId].tokenAddress = token;
        _tokenRaffles[raffleId].amount = amount;
        ...
    }
```
`_tokensLocked[USDC]` will be incremented by the deposit amount

Now let's look at the the withdraw function: 

```javascript
function withdrawToken(address token, uint256 amount) external onlyRole(0) {
        uint256 tokenBalance = IERC20(token).balanceOf(address(this));
        uint256 availableBalance;
        unchecked { availableBalance = tokenBalance - _tokensLocked[token]; }
        if (availableBalance < amount) revert InsufficientBalance();
        IERC20(token).safeTransfer(msg.sender, amount);
    }
```

If an admin wants to withdraw the locked funds, the available balance will be always 0 and cause a revert

Here is a scenario, confirming the vulnerability:

1. A USDC raffle admin, locks 1000 USDC, the `_tokensLocked[USDC]` will have value `1000e6`
2. A user participates in the raffle, but gets blacklisted by the USDC token, because of malicious acts for example
3. The user gets selected as winner, but he will not be able to claim his prize
4. The admin tries to withdraw his funds, but the values in the withdraw function will be as follows:
    - `tokenBalance` = 1000e6
    - `availableBalance` = 1000e6 - 1000e6 = 0
    - the check will fail -> `if (0 < 1000e6)`

Funds will be permanently stuck in the contract

## Impact

- Impact: High, as the locked tokens can't ever be withdrawn
- Likelihood: Low, as it requires a USDC blacklisted user to be selected as a winner
- Overall: Medium 

## Code Snippet

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesPrizeManager.sol#L207-L209
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesPrizeManager.sol#L218-L223

## Tool used

Manual Review

## Recommendation

Implement a mechanism that checks for user blacklists, but since the user can get blacklisted after he enters the raffle, if a winner is blacklisted allow the withdrawal of the locked amount or set a grace period for a winner to be able to claim his tokens, when the period ends and if the prize is still unclaimed, the locked funds are automatically unlocked.

**Comment by Blngogo** [comment]
@WangSecurity Sir can you have a look at this issue? Would like to hear your opinion

**Comment by fuzzysquirrel1032** [comment]
#70 is a dup similar to this
