### ISSUE TITLE
neko_nyaa - Out-of-gas revert in `WinnablesTicket.ownerOf()` may prevent raffles from settling, locking prizes in the Manager

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#339]
neko_nyaa

Medium

# Out-of-gas revert in `WinnablesTicket.ownerOf()` may prevent raffles from settling, locking prizes in the Manager

### Summary

`WinnablesTicket.ownerOf()` has a potentially lengthy while loop that reads through storage. We show a scenario where if a winner have bought too many tickets, they may be unable to claim their winnings 

### Root Cause

We examine the function `ownerOf()`:

```solidity
function ownerOf(uint256 id, uint256 ticketId) public view returns (address) {
    // ...
    while (_ticketOwnership[id][ticketId] == address(0)) { // @audit storage-read loop
        unchecked { --ticketId; } 
    }
    // ...
}
```

It finds the owner of a ticket by looping backwards until finding a match. For example, if:
- Alice owns tokens 0, 1, 2, 3, 4
- Bob owns tokens 5, 6, 7
- Charlie owns tokens 8, 9, 10, 11

Then `_ticketOwnership[0] = Alice`, `_ticketOwnership[5] = Bob`, `_ticketOwnership[8] = Charlie`, all other ownerships are `address(0)`.

The Avalance block gas limit is 15 million gas. Each storage read costs 2100 gas, which allows room for about ~7142 storage reads. Offsetting the intrinsic gas cost and other gas costs, we can estimate the number to be about 7100.

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L472

Per the contest README, on the limit of the number of tickets:

> `WinnablesTicketManager::buyTickets()` take a `uint16` argument for `ticketCount`. That means the maximum number of tickets that can be purchased in a single transaction is `type(uint16).max`

The maximum value of the `uint16` type is $2^{16} - 1 = 65535$, i.e. much larger than the upper limit of storage reads. Furthermore, note that the maximum supply is `uint32`. When `propagateRaffleWinner()` is called, it then internally calls into `_getWinnerByRequestId()`, which calls into the `IWinnablesTicket(TICKETS_CONTRACT).ownerOf()` which will revert due to OOG if the player has bought too many tickets at once.

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L338

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L476

Then propagation of results will be unsuccessful, and the prize will be stuck on the Ethereum Mainnet side without methods to retrieve it.

### Internal pre-conditions

- The winner has to have bought more than $7100$ (approx.) ticket in one tx. The winning ticket should be anything with an ID of $7100$ or more within its consecutive interval.

### Impact

Winner may not be able to withdraw their rewards due to OOG. Since the admin also cannot withdraw the rewards, they are permanently stuck in the contract.

Breaks the following invariant in the README:
> Winnables admins cannot do anything to prevent a winner from withdrawing their prize

As the Winnables admin can accept a signature to buy a large number of tickets from any participant.

### Mitigation

A proposed solution is that: 
- When a new range of ticket is minted, push the first ticket's ID into a storage array.
- In `ownerOf()`, binary search for the first ticket ID that is lower or equal to the ticket being looked up. Then return `_ticketOwnership` of the found ticket.  

Note that this is possible because the IDs array is sorted in ascending order. 

Duplicate of #398

**Comment by neko-nyaa** [comment]
Escalate. This submission has mentioned all the relevant information in the README, which is the highest source of truth, and how these assumptions lead to a scenario that breaks a core invariant also defined in the README. Hence this is at least a medium.

**Comment by mystery0x** [comment]
This is being linked to #142 where the sponsor has disputed this finding alleging it would require admin mistake via the API misconfiguration allowing players to buy excessive amount of tickets, as already clarified in the discord channel.

As such, this finding will be low at best.

**Comment by WangSecurity** [comment]
Planning to accept the escalation and duplicate with https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/398. For details, look at the discussion there.

**Comment by WangSecurity** [comment]
Result:
Medium
Duplicate of #398

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [neko-nyaa](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/339/#issuecomment-2329321588): accepted

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/12
