### ISSUE TITLE
irresponsible - admin can claim proceeds without allowing the winner to claim the prize

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#351]
irresponsible

High

# admin can claim proceeds without allowing the winner to claim the prize

### Summary

The admin can withdraw raffle proceeds without a winner being able to claim the prize.

### Root Cause

In WinnablesTicketManager.sol: 334
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L334

the `propagateRaffleWinner` function will check if a raffle is fulfilled and then the function will send the ccip message to the `WinnablesPrizeManager` on the other chain, finally the function will unlock the locked eth for the admin to withdraw, we can observe the following below
```solidity
    function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.FULFILLED) revert InvalidRaffleStatus();
        raffle.status = RaffleStatus.PROPAGATED;
        address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);

        _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner));
        IWinnablesTicket(TICKETS_CONTRACT).refreshMetadata(raffleId);
        unchecked {
            _lockedETH -= raffle.totalRaised;
        }
    }
```
As we can see the admin has the power to pick the chain selector, this is where the admin can set the chainSelector to another chain that does not have the `WinnablesPrizeManager`, this will send the ccip message to the incorrect chain and thus not allow the winner to claim the prize on the correct chain. Additionally the admin can now withdraw the proceeds all while the deserved winner cannot claim his prize.

from the read me

> The principles that must always remain true are:
> - Winnables admins cannot do anything to prevent a winner from withdrawing their prize
> - Participants in a raffle that got cancelled can always get refunded
> - Admins cannot affect the odds of a raffle

The first bullet point was violated so this validates the issue.

### Internal pre-conditions

1. a raffle must be fulfilled
2. the prize must be locked

### External pre-conditions

none

### Attack Path

1. the oracle fulfils the random word
2. winner is picked
3. admin calls `propagateRaffleWinner` with the incorrect chainSelector
4. the locked proceeds become unlocked but the winner cannot claim the prize
5. the admin withdraws the funds

### Impact

Main invariant of the protocol is not holding, users are essentially robbed of their prize/ loss of user funds.

### Mitigation

Allow the admin to not pick the chainSelector, this value should be set by the logic based on the raffleId to mitigate this  issue.

Duplicate of #50

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/22
