### ISSUE TITLE
Hama - An attacker will claim nft prizes from canceled raffles, resulting in a loss for the protocol.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#354]
Hama

High

# An attacker will claim nft prizes from canceled raffles, resulting in a loss for the protocol.

### Summary

The missing check for rafflePrize.status in the claimPrize() function will cause unauthorized prize claims for the protocol as an attacker can claim prizes from canceled raffles by simply providing a valid raffle ID.

### Root Cause

In [WinnablesPrizeManager.sol:111](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L111), there is a missing status check in the claimPrize() function that should verify if the raffle has been canceled before allowing the prize to be claimed.

[WinnablesPrizeManager.sol:L285](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L285) also in cancelRaffle() it only set _nftlocked to false, which it still exist in the contract.

### Internal pre-conditions

Users call to cancelRaffle() to set the raffle status to CANCELED.

### External pre-conditions

Attacker has knowledge of a canceled raffleId.

### Attack Path

users calls cancelRaffle() and marks the raffle as CANCELED.
The attacker identifies a canceled raffle id by monitoring the blockchain for PrizeUnlocked() events.
The attacker calls claimPrize() with the canceled raffle ID and successfully receives the prize.

### Impact
The protocol suffers a loss of valuable NFTs as the attacker gains access to canceled raffle prizes, potentially including rare or high-value assets, leading to financial loss and disruption to the raffle system.

### Mitigation

Add a check in the claimPrize() function to ensure the raffle's status is not CANCELED before proceeding with the prize distribution.

**Comment by hama-tech** [comment]
@WangSecurity
