### ISSUE TITLE
petro1912 - Incorrect use of arithmatic comparison operator in `WinnablesTicketManager` contract causes a restriction for an admin that admin can withdraw only full LINK token  balance of contract.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#356]
petro1912

Medium

# Incorrect use of arithmatic comparison operator in `WinnablesTicketManager` contract causes a restriction for an admin that admin can withdraw only full LINK token  balance of contract.

### Summary

Incorrect use of arithmatic comparison operator in `WinnablesTicketManager` contract causes a restriction for an admin that admin can withdraw only full LINK token  balance of contract.
If admin withdraws full LINK token balance from the contract, then contract can't send any CCIP message due to lack of fee.
Any transaction to withdraw a specific part of balance will be reverted to this issue, so admin can't withdraw LINK token.

### Root Cause

In [WinnablesTicketManager::withdrawTokens - L295](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L295), `<` operator was used instead of `>`.
```solidity
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
        if (amount < balance) revert InsufficientBalance();
``` 
- As you can see in above code, following condition should be met for withdrawal. `amount >= balance`
- However, maximum withdrawal amount is just 'balance', so amount should not be greater than 'balance'. `amont <= balance`.
So Admin should withdraw all balance of token to withdraw successfully.

### Impact

Admin can't withdraw a part of LINK token balance from the contract, but only full balance.
If admin withdraws full LINK token balance from the contract, then contract can't send any CCIP message due to lack of fee.
Any transaction to withdraw a part of balance will be reverted to this issue, so admin can't withdraw LINK token.

### Mitigation

Please use correct operator.
```diff
 function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
-       if (amount < balance) revert InsufficientBalance();
+       if (amount > balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/6
