### ISSUE TITLE
Hama - A user will fail to receive certain NFTs correctly, leading to unintended behaviors in the protocol and potential loss of the NFT.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#359]
Hama

Medium

# A user will fail to receive certain NFTs correctly, leading to unintended behaviors in the protocol and potential loss of the NFT.

### Summary

The use of transferFrom() instead of safeTransferFrom() in _sendNFTPrize() will cause issues for NFTs that rely on logic in the onERC721Received() function, potentially leading to loss of NFTs or failed transfers.

### Root Cause

[WinnablesPrizeManager.sol#L301](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L301) the _sendNFTPrize() function uses transferFrom() instead of safeTransferFrom() for NFT transfers, which does not trigger the onERC721Received() function for NFTs that rely on this callback.

### Internal pre-conditions

Admin needs to set up an NFT raffle with an NFT that implements custom logic in the onERC721Received() function.
The raffle prize must be claimed by a user.
The _sendNFTPrize() function must be executed.

### External pre-conditions

The NFT contract must have logic in the onERC721Received() function that expects to be called when receiving the NFT.

### Attack Path

The attacker identifies an NFT raffle using an NFT with custom logic in the onERC721Received() function.
The attacker wins the raffle and claims the NFT.
The _sendNFTPrize() function uses transferFrom(), bypassing the onERC721Received() function, potentially breaking the NFT's intended behavior.

### Impact

The user may not receive the NFT correctly, causing protocol disruption or loss of the NFT. Some NFTs may not function as expected, resulting in failed transfers or other unexpected behavior.

### Mitigation

Call the safeTransferFrom() method instead of transferFrom() for all NFT transfers to ensure that the onERC721Received() function is triggered for NFTs that depend on it.

**Comment by hama-tech** [comment]
@WangSecurity
