### ISSUE TITLE
Pro_King - Incorrect Condition in `WinnablesTicketManager::withdrawTokens` Function Causes Token Transfer Failure

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#360]
Pro_King

High

# Incorrect Condition in `WinnablesTicketManager::withdrawTokens` Function Causes Token Transfer Failure

## Description

The `WinnablesTicketManager::withdrawTokens` function contains a logical error in the condition that checks whether the requested withdrawal amount exceeds the contract's token balance. The current condition is written as `if (amount < balance) revert InsufficientBalance();`, which is incorrect. This causes the function to transfer tokens when the requested amount is greater than the balance, which is both incorrect and dangerous.
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L290C3-L297C6

## Impact

This issue causes tokens transfer failure in the contract because if the requested amount is greater than the contract’s balance, it will incorrectly proceed with the transfer which will fail. If the amount is less than the balance, it will incorrectly revert the transaction with the `InsufficientBalance()` error. As a result, token transfers are effectively impossible under this faulty logic. 

## Tool used

Manual Review

## Recommendation

To correct the logic, the condition should be modified to properly check if the requested amount is greater than the contract's balance so then it will revert otherwise it transfer tokens. The corrected condition should be:
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L290C3-L297C6
```diff
  function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
      
        uint256 balance = token.balanceOf(address(this));
-        if (amount < balance) revert InsufficientBalance();
+        if (amount > balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/6
