### ISSUE TITLE
Hama - propagateRaffleWinner Vulnerable to Repeated Calls Due to Missing Status Recheck

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#362]
Hama

High

# propagateRaffleWinner Vulnerable to Repeated Calls Due to Missing Status Recheck

### Summary

The propagateRaffleWinner function can be called multiple times because it does not reset raffle.totalRaised to 0 and does not recheck the raffle status, allowing an attacker to repeatedly trigger prize propagation and cause financial loss.

### Root Cause

[WinnablesTicketManager.sol#L337](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L337), the propagateRaffleWinner function sets the raffle status to PROPAGATED without checking if it has been  propagated. 
Additionally, it does not reset raffle.totalRaised to 0, leading to potential re-execution of prize propagation.

### Internal pre-conditions

The propagateRaffleWinner function is called with a valid raffleId for a raffle that has not been fully processed.
The raffle status must be FULFILLED before the function is called.
The totalRaised amount is not reset to 0 after propagation.

### External pre-conditions

The prize manager contract must be available to receive cross-chain messages.
Chainlink Request ID must be valid for fetching the winner.

### Attack Path

An attacker calls propagateRaffleWinner with a raffleId that is in the FULFILLED status.
Since raffle.status is only set to PROPAGATED without checking if it was already set, the function can be called multiple times.
Each call subtracts the raffle.totalRaised amount from _lockedETH, potentially draining funds.

### Impact

The protocol suffers a loss of locked ETH, as the function allows multiple deductions from _lockedETH due to repeated calls. This can lead to financial loss and potential imbalance in the raffle system.

### Mitigation

Add a check to ensure that the propagateRaffleWinner function can only be executed once per raffle by verifying the current status before setting it to PROPAGATED. Additionally, reset raffle.totalRaised to 0 after processing.

**Comment by hama-tech** [comment]
@WangSecurity
