### ISSUE TITLE
petro1912 - Having both possibilities at the minTicketsThreshold can lead to inconsistencies in the raffle process, as it allows a raffle to be drawable and cancelable simultaneously.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#368]
petro1912

Medium

# Having both possibilities at the minTicketsThreshold can lead to inconsistencies in the raffle process, as it allows a raffle to be drawable and cancelable simultaneously.

### Summary

The drawable and cancelable states are incompatible, so the conditions for both states must be exclusive.
However in `_checkShouldDraw` and `_checkShouldCancel` of `WinnablesTicketManager` contract, if supply is exact equal to `minTicketsThreshold`, raffle can be drawable and cancelable simultaneously.
This dual state can create confusion and undermine the integrity of the raffle system.

### Root Cause

In [`WinnablesTicketManager::_checkShouldDraw`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L431), check if current supply is not less than `minTicketsThreshold`, and in  [`WinnablesTicketManager::_checkShouldCancel`](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L440), check if current supply is not greater than `minTicketsThreshold`.

So if current supply is `minTicketsThreshold`, then pass the both of validations, so raffle can be drawable and cancelable simultaneously in rare case.

### Impact

This dual state can cause confusion and compromise the integrity of the raffle system.
The raffle state is determined based on the first caller to execute one of the two functions.
This breaks the integrity of the contract in the rare case where the current supply is exactly equal to `minTicketsThreshold`.

### Mitigation

Please fix to remove overlapped condition.

```diff
function _checkShouldDraw(uint256 raffleId) internal view {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.IDLE) revert InvalidRaffle();
        uint256 currentTicketSold = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
        if (currentTicketSold == 0) revert NoParticipants();

        if (block.timestamp < raffle.endsAt) {
            if (currentTicketSold < raffle.maxTicketSupply) revert RaffleIsStillOpen();
        }
-       if (currentTicketSold < raffle.minTicketsThreshold) revert TargetTicketsNotReached();
+       if (currentTicketSold <= raffle.minTicketsThreshold) revert TargetTicketsNotReached();
    }
```
or

```diff
function _checkShouldCancel(uint256 raffleId) internal view {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status == RaffleStatus.PRIZE_LOCKED) return;
        if (raffle.status != RaffleStatus.IDLE) revert InvalidRaffle();
        if (raffle.endsAt > block.timestamp) revert RaffleIsStillOpen();
        uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
-        if (supply > raffle.minTicketsThreshold) revert TargetTicketsReached();
+        if (supply >= raffle.minTicketsThreshold) revert TargetTicketsReached();
}
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/23
