### ISSUE TITLE
Hama - An attacker can reuse signatures across chains for unauthorized ticket purchases, causing financial loss for the protocol.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#396]
Hama

Medium

# An attacker can reuse signatures across chains for unauthorized ticket purchases, causing financial loss for the protocol.

### Summary

The lack of chain-specific information in the _checkPurchaseSig function makes the contract vulnerable to cross-chain replay attacks. An attacker can reuse valid signatures from one chain to perform unauthorized actions on another, causing unauthorized ticket purchases and potential financial loss.

### Root Cause

[WinnablesTicketManager.sol#L453](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L453)the _checkPurchaseSig function does not include the chain ID in the signature verification process, allowing replay attacks across different chains.

### Internal pre-conditions

The attacker obtains a valid signature for a ticket purchase on one chain.
The attacker uses the same signature on a different chain.

### External pre-conditions

The signature is valid and has not expired.
The contract is deployed on multiple chains, ethereum and avalanche as stated.

### Attack Path

The attacker acquires a valid signature for a specific ticket purchase.
The attacker reuses the signature on another chain to perform an unauthorized ticket purchase.

### Impact

The protocol suffers financial loss due to unauthorized ticket purchases enabled by replay attacks. This undermines the integrity of the ticketing system and causes potential revenue loss.

### Mitigation

Include the chain ID in the EIP-712 signature verification process to ensure that signatures are unique to each chain, preventing replay attacks.

**Comment by hama-tech** [comment]
@WangSecurity
