### ISSUE TITLE
NoOne - Incorrect balance check logic causes `withdrawTokens` function to fail

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#78]
NoOne

High

# Incorrect balance check logic causes `withdrawTokens` function to fail

## Summary
The [withdrawTokens](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292) function in the contract has a critical logical error in its balance check. The current check incorrectly prevents valid withdrawals, leading to potential operational disruptions and locked funds. This issue arises from the incorrect condition used to compare the requested withdrawal `amount` with the contract’s token `balance`.
## Vulnerability Detail
The `withdrawTokens` function checks if the amount to be withdrawn is `less than` the contract’s `balance` (balance). If this condition is met, the function reverts with an `InsufficientBalance` error. 
The incorrect condition leads to the function reverting for all valid withdrawal requests where `amount` is `less than` `balance`, making it `impossible` to withdraw tokens even when the contract has sufficient balance. This error affects the fundamental operation of the function, preventing the intended recovery or management of tokens.
## Impact
* Operational Breakdown: The primary impact is that the withdrawTokens function will not operate as expected, preventing the withdrawal of tokens. This results in the function being effectively unusable in most scenarios.
* Locked Funds: Tokens that are intended to be recoverable or manageable by the admin will remain locked in the contract. This could prevent the admin from accessing or retrieving tokens accidentally sent to the contract.
* Disruption: The issue could disrupt contract operations, especially if the contract is meant to handle substantial amounts of ERC20 tokens or if the tokens need to be periodically withdrawn.
## Code Snippet
```solidity
 function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
        if (amount < balance) revert InsufficientBalance();  <---
        token.safeTransfer(msg.sender, amount);
    }
```
## Tool used

Manual Review

## Recommendation
```solidity
function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
    IERC20 token = IERC20(tokenAddress);
    uint256 balance = token.balanceOf(address(this));
    if (amount > balance) revert InsufficientBalance(); // Correct check
    token.safeTransfer(msg.sender, amount);
}
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/6
