### ISSUE TITLE
jennifer37 - The admin can manipulate the raffle winner after randomword is generated.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#88]
jennifer37

High

# The admin can manipulate the raffle winner after randomword is generated.

## Summary
When `randomWord` is set via ChainLink VRF, the winner will be determined via `request.randomWord % supply`. However, the miner role still can mint for this raffle to increase the `supply`. So the admin role/miner role can manipulate the winner result.

## Vulnerability Detail
When the bought phase is over and reaches the condition, we can request one random word to determine this raffle's winner via `drawWinner`. The `drawWinner` will send to request to ChainLink VRF. ChainLink VRF will response and update variable `randomWord`. Now anyone can trigger `propagateRaffleWinner()` to calculate the final winner to send message to Ethereum. And the winner can claim his prize.
The problem is that the winner is determined via `request.randomWord % supply`. After the ChainLink VRF update `request.randomWord`. The miner can still mint this raffle to manipulate `supply`. This will cause the miner role/admin role can manipulate the final winner result.
In readme, our sponsor mentions that `Admins cannot affect the odds of a raffle.` It means that the admin role should not be seen as trusted. And the admin role can manipulate the final winner result. 
```solidity
    function drawWinner(uint256 raffleId) external {
        ...
        uint256 requestId = VRFCoordinatorV2Interface(VRF_COORDINATOR).requestRandomWords(
            KEY_HASH,
            SUBSCRIPTION_ID,
            3,
            100_000,
            1
        );
        _chainlinkRequests[requestId] = RequestStatus({
            raffleId: raffleId,
            randomWord: 0
        });
        raffle.chainlinkRequestId = requestId;
        ...
    }
```
```solidity
    function fulfillRandomWords(
        uint256 requestId,
        uint256[] memory randomWords
    ) internal override {
        ...
        request.randomWord = randomWords[0];
        ...
    }
```
```solidity
    function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        ...
        address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);
        ...
    }
    function _getWinnerByRequestId(uint256 requestId) internal view returns(address) {
        RequestStatus storage request = _chainlinkRequests[requestId];
        uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(request.raffleId);
        uint256 winningTicketNumber = request.randomWord % supply;
        return IWinnablesTicket(TICKETS_CONTRACT).ownerOf(request.raffleId, winningTicketNumber);
    }
```
```solidity
  function mint(address to, uint256 id, uint256 amount) external onlyRole(1) {
    ...
    address operator = msg.sender;
    uint256 startId = _supplies[id];
    unchecked {
      _balances[id][to] += amount;
      _supplies[id] = startId + amount;
    }
    _ticketOwnership[id][startId] = to;
   ...
  }
```

## Impact
The admin role can manipulate the raffle final winner result via minting raffle.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345

## Tool used

Manual Review

## Recommendation
When the raffle status is not `IDLE` status, the miner should not mint raffle for anyone.

Duplicate of #129

**Comment by WangSecurity** [comment]
This issue will be validated and duplicated with #129. Look at the discussion there for context.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/20
