### ISSUE TITLE
jennifer37 - Admin role can manipulate the winner role via adding another CCIP counter part

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#98]
jennifer37

High

# Admin role can manipulate the winner role via adding another CCIP counter part

## Summary
In WinnablesPrizeManager, the contract will set each raffle's winner via message from valid counterpart. In normal case, there is only one valid counterpart, Avalanche::WinnablesTicketManager. If the admin role adds another valid counterpart, and sent the manipualted message from the added counterpart, the winner result may be manipulated by the admin.

## Vulnerability Detail
In WinnablesPrizeManager, we will receive message via CCIP. If the message comes from the valid counterpart, we will parse the message and set the winner for this raffle.
The problem is that the admin role can set one new valid counterpart. The admin role can send one manipulated message from the newly added counterpart before the actual real counterpart send the real message to WinnablesPrizeManager and set the winner to anyone he wants. 
In readme, the sponsor mentions that `Admins cannot affect the odds of a raffle.` Now the admin role can determine the final winner directly. 
```solidity
    function _ccipReceive(
        Client.Any2EVMMessage memory message
    ) internal override {
        (address _senderAddress) = abi.decode(message.sender, (address));
        // Check the msg's source chain and source contract.
        bytes32 counterpart = _packCCIPContract(_senderAddress, message.sourceChainSelector);
        if (!_ccipContracts[counterpart]) revert UnauthorizedCCIPSender();
       ...
        (raffleId, winner) = _decodeWinnerDrawnMessage(message.data);
        _rafflePrize[raffleId].winner = winner;
        emit WinnerPropagated(raffleId, winner);
    }
```
```solidity
    function setCCIPCounterpart(
        address contractAddress,
        uint64 chainSelector,
        bool enabled
    ) external onlyRole(0) {
        _setCCIPCounterpart(contractAddress, chainSelector, enabled);
    }
```
## Impact
The admin role can manipulate the raffle winner via adding another valid counterpart.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesPrizeManager.sol#L260-L278

## Tool used

Manual Review

## Recommendation
Limit changing the counterpart after we `setCCIPCounterpart` once in the initialization process.

Duplicate of #277

**Comment by WangSecurity** [comment]
This issue will be validated and duplicated with #129. Look at the discussion there for context.
