### ISSUE TITLE
jennifer37 - Winner may not claim his rewards if the winner in avalanche is one abstract account

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#99]
jennifer37

Medium

# Winner may not claim his rewards if the winner in avalanche is one abstract account

## Summary
In one raffle game, the winner in Avalanche is allowed to claim rewards in Ethereum. Considering that the participant winner is one abstract account, the winner in Avalanche may not control the same address in Ethereum. The winner may not claim the rewards.

## Vulnerability Detail
In function propagateRaffleWinner(), we will calculate the final winner in one raffle, and send the winner address in Avalanche to the Ethereum. And the winner can claim the related rewards in Ethereum.
The problem is that winner in Avalanche may not control the same address in Ethereum, for example, abstract account. This will cause that the winner cannot claim rewards.
```solidity
    function propagateRaffleWinner(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.FULFILLED) revert InvalidRaffleStatus();
        raffle.status = RaffleStatus.PROPAGATED;
        address winner = _getWinnerByRequestId(raffle.chainlinkRequestId);

        _sendCCIPMessage(prizeManager, chainSelector, abi.encodePacked(uint8(CCIPMessageType.WINNER_DRAWN), raffleId, winner));
        IWinnablesTicket(TICKETS_CONTRACT).refreshMetadata(raffleId);
        unchecked {
            _lockedETH -= raffle.totalRaised;
        }
    }
```

## Impact
Winner may not claim rewards in Ethereum if the winner in Avalanche is one abstract account.

## Code Snippet
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345
## Tool used

Manual Review

## Recommendation
Only the winner can trigger propagateRaffleWinner() and add another parameter `claimer`. The winner in avalanche can assign one address `claimer` in Ethereum to claim this reward.

**Comment by WangSecurity** [comment]
This issue will be validated with medium severity and duplicated with #122. For more info, refer to [this comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2348780200).
